name: dartchess
description: Native mobile chess rules library
version: 1.0.0
platforms:
  android:
  ios:
  linux:
  macos:
  windows:
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.5 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
