name: dartchess
description: Native mobile chess rules library
version: 0.1.0
platforms:
  android:
  ios:
  linux:
  macos:
  windows:
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  fast_immutable_collections: ^9.0.0
  meta: ^1.8.0

dev_dependencies:
  benchmark: ^0.3.0
  lint: ^2.0.1
  test: ^1.16.0
